# default variables


# for ntp
ntp_servers:
 - 0.ubuntu.pool.ntp.org
 - 1.ubuntu.pool.ntp.org
 - 2.ubuntu.pool.ntp.org
 - 3.ubuntu.pool.ntp.org
# for git
git_user_name: git
git_user_email: git@localhost

# for ruby
ruby_version: 2.2.0
