# default variables

# for apt-get
apt_upgrade: false

# for git
git_user: git
git_email: git@localhost

# for mysql
mysql_listen_port: 3306
mysql_root_password: ''

# for ntp
ntp_servers:
  - 0.ubuntu.pool.ntp.org
  - 1.ubuntu.pool.ntp.org
  - 2.ubuntu.pool.ntp.org
  - 3.ubuntu.pool.ntp.org

# for snmp
snmp_enable_trapd: false

# for ruby
ruby_version: 2.2.0

# for zabbix
zbx_hostname: hostname_must_override
zbx_server: zabbix_server
zbx_user: zabbix
zbx_pass: zabbix
zbx_db: zabbix
